# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IosFitnessApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IosFitnessApp

  target 'IosFitnessAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IosFitnessAppUITests' do
    # Pods for testing
  end

end
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'